### PR TITLE
chore(Elixir): fix warnings emitted from v1.17.0

### PR DESCRIPTION
**Pull request by tomciopp**
@voltone Let me know if you have any questions.

### CODE REVIEW

**Comment by voltone** [comment]
Thanks for your PR! I just merged #73 and it formats the code using a more recent formatter that uses charlist sigils. I believe that supersedes this PR, am I right?

**Comment by tomciopp** [comment]
@voltone That PR handles most of the issues, but there are still some charlists in doctests. I can push another PR that just handles those.

**Comment by tomciopp** [comment]
@voltone There is also a warning thrown by the deprecated, `System.get_pid/0` function. However I have left that out of the new PR as it looks like the replacement `System.pid` has only been around since Elixir version 1.9.0.

**Comment by voltone** [comment]
> @voltone There is also a warning thrown by the deprecated, `System.get_pid/0` function. However I have left that out of the new PR as it looks like the replacement `System.pid` has only been around since Elixir version 1.9.0.

I know, and since it is only used in tests I don't see much reason to drop support for Elixir < 1.9 just for that...

**Comment by voltone** [comment]
Superseded by #73 and #74

**Pull request closed without merging**
