### PR TITLE
fix(test_server): deprecated ssl_accept

### PR DESCRIPTION
**Pull request by victorolinasc**
OTP 21 deprecated the `:ssl.ssl_accept/3` function. So, we add a
compile check to determine which function to call. This library
supports Elixir 1.5 and so the OTP support must be present up to OTP 18.

### CODE REVIEW

**Comment by voltone** [comment]
Thanks for that, and sorry for the delay. I would actually prefer to avoid `apply/3`, and instead define a private function that calls either `accept` or `handshake` (like [here](https://github.com/voltone/plug_signature/blob/master/lib/plug_signature/crypto.ex#L153)). What do you think?

**Comment by victorolinasc** [comment]
Fine for me :) Will update accordingly.

**Comment by victorolinasc** [comment]
Updated!

**Comment by voltone** [comment]
> Updated!

Excellent. Thanks!

Will merge and publish 0.8.5 now.

**Pull request merged**
